backend:
  image: gabrielmunumel/phonic-ai-backend:latest
  replicas: 1

frontend:
  image: gabrielmunumel/phonic-ai-frontend:latest
  replicas: 1

redis:
  image: redis:7
  replicas: 1

ingress:
  enabled: true
  certificateArn: ""
  host: phonic-ai.stackedge.dev

namespace: phonic-ai
