backend:
  image: 177539010329.dkr.ecr.eu-central-1.amazonaws.com/phonic-ai-backend:latest
  replicas: 1

frontend:
  image: 177539010329.dkr.ecr.eu-central-1.amazonaws.com/phonic-ai-frontend:latest
  replicas: 1

redis:
  image: redis:7
  replicas: 1

ingress:
  enabled: true
  certificateArn: arn:aws:acm:eu-central-1:177539010329:certificate/ecb39198-2d7a-488c-bf43-8ba1d664c3a0
  host: stackedge.dev
